/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATypographyTitle: typeof import('ant-design-vue/es')['TypographyTitle']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
  const ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
  const AButton: typeof import('ant-design-vue/es')['Button']
  const AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
  const ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
  const ALayout: typeof import('ant-design-vue/es')['Layout']
  const ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
  const ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
  const ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
  const ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
  const AMenu: typeof import('ant-design-vue/es')['Menu']
  const AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
  const ASpace: typeof import('ant-design-vue/es')['Space']
  const ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
  const ATypographyTitle: typeof import('ant-design-vue/es')['TypographyTitle']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}